# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 549a035a5950a7c7abc0ddd9a6bbfadee3a56a51a10a395a69b0e6466ae4c56435e845f919bde8e76a9fbb3cb6293a51815373098ed8899c1996090aab9c1a73

test:
  secret_key_base: 9ddf6998c311d70f8feba9d62165f10ae72368249f6faf066174f372e5f1c10f2d52242b141dfd8667ab6cd22804a26ae6ddc0283a83ad6df1584160a88806ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
