# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: decc4a8434c15ce5eb95ab17cb529b60e042a049bb92f4fa12c5314161ab68901f3fa33322dec411f9ac8c4e01327ff0210fe583d3ed6b47b9afe1c0b4d1e4da

test:
  secret_key_base: 371b46898a200193076e14f3ab195a40431fb7934848c72bcdcaadfb7448c5e498fc69d97eb1304a62f9f2505ec01385bec2fe632fb96d0bcf18b89ad8642e37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
