# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ead6115b852ed1905bec6e7d234f5bb9f345311908eb943808666612d28740f5a1b7fdf18e966e228401b50674066af5761feab43e27145620ebb6b7bd1dd237

test:
  secret_key_base: 4d610914b58bc015595bc70c42cc92339ed3e1ce60cc0093b8eb22e974e35d2e6df81ec7471a313e62f7c0c772c128f1d562c2a8991e9997d7ceb9cb468e03d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
